Repository BasisResearch/chirho, pull requests merged in 2023-08, with the labels that each got.

#142 Add preempt operation
  chirho/counterfactual/handlers/counterfactual.py
  chirho/counterfactual/ops.py
  chirho/indexed/ops.py
  tests/counterfactual/test_counterfactual_handler.py
Labels: enhancement, status:awaiting review, feature:causality

#229 Cut Posterior Implementation + Examples
  chirho/counterfactual/handlers/selection.py
  chirho/indexed/handlers.py
  chirho/observational/handlers/cut.py
  docs/source/dr_learner.ipynb
  docs/source/sdid.ipynb
  tests/observational/test_cut_posterior_modules.py
Labels: status:awaiting review, feature:causality

#233 SDID and DR-learner example formatting changes
  docs/source/dr_learner.ipynb
  docs/source/sdid.ipynb
Labels: documentation, status:awaiting review, examples

#231 Add cut and examples to Sphinx docs
  README.rst
  docs/source/index.rst
  docs/source/observational.rst
Labels: documentation, status:awaiting review

#232 Bump version to 0.1.0-alpha2
  setup.py
Labels: status:awaiting review, misc-release
