Repository BasisResearch/chirho, pull requests merged in 2023-11, with the labels that each got.

#364 Fixed SDID bug
  docs/source/sdid.ipynb
Labels: status:awaiting review

#374 Separate cond_n and scatter_n from cond and scatter
  chirho/counterfactual/handlers/explanation.py
  chirho/counterfactual/ops.py
  chirho/indexed/ops.py
  chirho/observational/handlers/cut.py
  tests/indexed/test_internals.py
Labels: status:awaiting review, refactor, feature:dynamics

#361 Simplify and speed up InterruptionEventLoop
  chirho/dynamical/handlers/__init__.py
  chirho/dynamical/handlers/event_loop.py
  chirho/dynamical/handlers/interruption.py
  chirho/dynamical/handlers/solver.py
  chirho/dynamical/handlers/trajectory.py
  chirho/dynamical/internals/_utils.py
  chirho/dynamical/internals/backends/torchdiffeq.py
  chirho/dynamical/internals/solver.py
  chirho/dynamical/ops.py
  tests/dynamical/test_solver.py
Labels: enhancement, status:awaiting review, refactor, feature:dynamics

#378 Speed up parallelized CI
  .github/workflows/test.yml
Labels: status:awaiting review, testing

#332 One-sided runtime check of whether a `dynamics` instance satisfies assumptions of a `solver`
  chirho/dynamical/handlers/event_loop.py
  chirho/dynamical/handlers/solver.py
  chirho/dynamical/internals/backends/torchdiffeq.py
  chirho/dynamical/internals/solver.py
  chirho/dynamical/ops.py
  tests/dynamical/test_validate_dynamics.py
Labels: enhancement, status:awaiting review, feature:dynamics

#383 Update tutorial_i.ipynb
  docs/source/tutorial_i.ipynb
Labels: bug, status:awaiting review, examples

#387 Add linting actions for Python 3.9 and 3.10
  .github/workflows/lint.yml
Labels: status:awaiting review, testing, misc-release

#389 Rename DoMessenger and ConditionMessenger query handlers
  chirho/interventional/handlers.py
  chirho/observational/handlers/condition.py
  tests/counterfactual/test_mediation.py
Labels: status:awaiting review, refactor

#391 Add `staging-*` to CI build
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: status:awaiting review, testing

#395 Merge InterruptionEventLoop into Solver
  chirho/dynamical/handlers/__init__.py
  chirho/dynamical/handlers/event_loop.py
  chirho/dynamical/handlers/solver.py
  chirho/dynamical/internals/solver.py
  chirho/dynamical/ops.py
  docs/source/dynamical_intro.ipynb
  tests/dynamical/test_dynamic_interventions.py
  tests/dynamical/test_handler_composition.py
  tests/dynamical/test_log_trajectory.py
  tests/dynamical/test_noop_interruptions.py
  tests/dynamical/test_solver.py
  tests/dynamical/test_static_interventions.py
  tests/dynamical/test_static_observation.py
  tests/dynamical/test_validate_dynamics.py
Labels: status:awaiting review, refactor, feature:dynamics

#399 Make interruption application a normal function call
  chirho/dynamical/handlers/interruption.py
  chirho/dynamical/internals/backends/torchdiffeq.py
  chirho/dynamical/internals/solver.py
  docs/source/dynamical_intro.ipynb
  tests/dynamical/test_dynamic_interventions.py
  tests/dynamical/test_noop_interruptions.py
Labels: status:awaiting review, refactor, feature:dynamics
