Repository BasisResearch/chirho, pull requests merged in 2023-10, with the labels that each got.

#293 Decouple `SimulatorEventLoop` from concatenation of trajectories
  chirho/dynamical/handlers/__init__.py
  chirho/dynamical/handlers/dynamical.py
  chirho/dynamical/handlers/interruption.py
  chirho/dynamical/handlers/trace.py
  chirho/dynamical/internals/ODE/backends/torchdiffeq.py
  chirho/dynamical/internals/ODE/ode_simulate.py
  chirho/dynamical/internals/dynamical.py
  chirho/dynamical/internals/interruption.py
  chirho/dynamical/ops/ODE.py
  chirho/dynamical/ops/dynamical.py
  docs/source/dynamical_intro.ipynb
  tests/dynamical/dynamical_fixtures.py
  tests/dynamical/obs_runtime.py
  tests/dynamical/test_dynamic_interventions.py
  tests/dynamical/test_handler_composition.py
  tests/dynamical/test_noop_interruptions.py
  tests/dynamical/test_solver.py
  tests/dynamical/test_state_trajectory.py
  tests/dynamical/test_static_interventions.py
  tests/dynamical/test_static_observation.py
  tests/dynamical/test_trace.py
Labels: status:awaiting review, refactor, feature:dynamics, staging-branch

#296 Add missing odeint_kwargs from `torchdiffeq_get_next_interruptions_dynamic`
  chirho/dynamical/internals/ODE/backends/torchdiffeq.py
Labels: bug, status:awaiting review, feature:dynamics, staging-branch

#298 Remove `ODEDynamics` subclass and corresponding `simulate` indirection through `ode_simulate`
  chirho/dynamical/handlers/ODE/__init__.py
  chirho/dynamical/handlers/ODE/ode.py
  chirho/dynamical/handlers/ODE/solvers/__init__.py
  chirho/dynamical/handlers/ODE/solvers/torchdiffeq.py
  chirho/dynamical/handlers/__init__.py
  chirho/dynamical/handlers/dynamical.py
  chirho/dynamical/handlers/interruption/__init__.py
  chirho/dynamical/handlers/interruption/array_observation.py
  chirho/dynamical/handlers/interruption/interruption.py
  chirho/dynamical/handlers/solver.py
  chirho/dynamical/handlers/trace.py
  chirho/dynamical/internals/ODE/__init__.py
  chirho/dynamical/internals/ODE/ode_simulate.py
  chirho/dynamical/internals/__init__.py
  chirho/dynamical/internals/dynamical.py
  chirho/dynamical/internals/indexed.py
  chirho/dynamical/internals/interruption.py
  chirho/dynamical/internals/interventional.py
  chirho/dynamical/internals/solver/__init__.py
  chirho/dynamical/internals/solver/torchdiffeq.py
  chirho/dynamical/ops/ODE.py
  chirho/dynamical/ops/__init__.py
  chirho/dynamical/ops/dynamical.py
  tests/dynamical/dynamical_fixtures.py
  tests/dynamical/obs_runtime.py
  tests/dynamical/test_dynamic_interventions.py
  tests/dynamical/test_handler_composition.py
  tests/dynamical/test_noop_interruptions.py
  tests/dynamical/test_solver.py
  tests/dynamical/test_static_interventions.py
  tests/dynamical/test_static_observation.py
  tests/dynamical/test_trace.py
Labels: status:awaiting review, refactor, feature:dynamics, staging-branch

#299 Migrate torchdiffeq dependency from "extras" to "install_requires"
  .github/workflows/lint.yml
  .github/workflows/test.yml
  docs/source/requirements.txt
  setup.py
Labels: status:awaiting response, feature:dynamics

#301 Simplify State and Trajectory types
  chirho/dynamical/internals/indexed.py
  chirho/dynamical/ops/dynamical.py
  tests/dynamical/test_dynamic_interventions.py
Labels: status:awaiting review, refactor, feature:dynamics

#302 Remove unused unsqueeze function
  chirho/dynamical/internals/dynamical.py
Labels: status:awaiting review, refactor, feature:dynamics

#304 Call DynamicTrace._reset on __enter__
  chirho/dynamical/handlers/trace.py
Labels: bug, status:awaiting review, feature:dynamics

#303 Clean up Trajectory.append
  chirho/dynamical/handlers/trace.py
  chirho/dynamical/ops/dynamical.py
  tests/dynamical/test_state_trajectory.py
Labels: status:awaiting response, refactor, feature:dynamics

#294 Adding helper function for generating stochastic interventions with approximately uniform distributions.
  chirho/counterfactual/handlers/explanation.py
  tests/counterfactual/test_handlers_explanation.py
Labels: status:awaiting review, feature:causality

#297 SearchForCause effect handler with tests thereof
  chirho/counterfactual/handlers/explanation.py
  tests/counterfactual/test_handlers_explanation.py
Labels: status:awaiting response, feature:causality

#306 Clean up random_intervention tests and docs
  chirho/counterfactual/handlers/explanation.py
  tests/counterfactual/test_handlers_explanation.py
Labels: status:awaiting review, refactor, testing, feature:causality

#307 Add default behavior for `X.t` with `torchdiffeq` solver.
  chirho/dynamical/internals/solver/torchdiffeq.py
  tests/dynamical/dynamical_fixtures.py
Labels: feature:dynamics

#309 Simplify SimulatorEventLoop logic
  chirho/dynamical/handlers/dynamical.py
  chirho/dynamical/handlers/interruption/array_observation.py
  chirho/dynamical/handlers/interruption/interruption.py
  chirho/dynamical/internals/interruption.py
  tests/dynamical/test_static_observation.py
Labels: status:awaiting review, refactor, feature:dynamics

#311 Rename NonInterruptingPointObservationArray to StaticBatchObservation
  chirho/dynamical/handlers/__init__.py
  chirho/dynamical/handlers/interruption/array_observation.py
  tests/dynamical/obs_runtime.py
  tests/dynamical/test_handler_composition.py
  tests/dynamical/test_static_observation.py
Labels: status:awaiting review, refactor, feature:dynamics

#310 Rename Dynamics to InPlaceDynamics
  chirho/dynamical/handlers/interruption/array_observation.py
  chirho/dynamical/handlers/interruption/interruption.py
  chirho/dynamical/internals/dynamical.py
  chirho/dynamical/internals/interruption.py
  chirho/dynamical/internals/solver/torchdiffeq.py
  chirho/dynamical/ops/__init__.py
  chirho/dynamical/ops/dynamical.py
  tests/dynamical/dynamical_fixtures.py
  tests/dynamical/test_dynamic_interventions.py
Labels: status:awaiting review, refactor, feature:dynamics

#314 Remove obsolete script from dynamical test suite
  tests/dynamical/obs_runtime.py
Labels: refactor, testing, feature:dynamics

#313 Remove unnecessary arguments from Interruptions
  chirho/dynamical/handlers/interruption/interruption.py
  chirho/dynamical/internals/solver/torchdiffeq.py
  docs/source/dynamical_intro.ipynb
  tests/dynamical/test_dynamic_interventions.py
  tests/dynamical/test_noop_interruptions.py
Labels: status:awaiting review, refactor, feature:dynamics

#312 Move dynamical backend interface into one file
  chirho/dynamical/handlers/__init__.py
  chirho/dynamical/handlers/dynamical.py
  chirho/dynamical/handlers/interruption/interruption.py
  chirho/dynamical/handlers/solver.py
  chirho/dynamical/handlers/trace.py
  chirho/dynamical/internals/__init__.py
  chirho/dynamical/internals/_utils.py
  chirho/dynamical/internals/backend.py
  chirho/dynamical/internals/dynamical.py
  chirho/dynamical/internals/interventional.py
  chirho/dynamical/internals/solver/torchdiffeq.py
  chirho/dynamical/ops/dynamical.py
  tests/dynamical/test_state_trajectory.py
Labels: status:awaiting review, refactor, feature:dynamics

#315 Remove some trivial dynamical test cases
  tests/dynamical/test_dynamic_interventions.py
  tests/dynamical/test_static_interventions.py
Labels: status:awaiting review, testing, feature:dynamics

#316 Reorder state and dstate in InPlaceDynamics and ObservableInPlaceDynamics
  chirho/dynamical/ops/dynamical.py
Labels: status:awaiting review, refactor, feature:dynamics

#317 Make Trajectory methods use indexed ops
  chirho/dynamical/handlers/trace.py
  chirho/dynamical/internals/_utils.py
  chirho/dynamical/internals/solver/torchdiffeq.py
  chirho/dynamical/ops/dynamical.py
Labels: status:awaiting review, refactor, feature:dynamics

#319 Rename dynamical submodules and components
  chirho/dynamical/handlers/__init__.py
  chirho/dynamical/handlers/event_loop.py
  chirho/dynamical/handlers/interruption.py
  chirho/dynamical/handlers/interruption/__init__.py
  chirho/dynamical/handlers/interruption/array_observation.py
  chirho/dynamical/handlers/solver.py
  chirho/dynamical/handlers/trajectory.py
  chirho/dynamical/internals/__init__.py
  chirho/dynamical/internals/_utils.py
  chirho/dynamical/internals/backends/__init__.py
  chirho/dynamical/internals/backends/torchdiffeq.py
  chirho/dynamical/internals/solver.py
  chirho/dynamical/ops.py
  chirho/dynamical/ops/__init__.py
  tests/dynamical/dynamical_fixtures.py
  tests/dynamical/test_dynamic_interventions.py
  tests/dynamical/test_handler_composition.py
  tests/dynamical/test_log_trajectory.py
  tests/dynamical/test_noop_interruptions.py
  tests/dynamical/test_solver.py
  tests/dynamical/test_state_trajectory.py
  tests/dynamical/test_static_interventions.py
  tests/dynamical/test_static_observation.py
Labels: status:awaiting review, refactor, feature:dynamics

#322 Remove var_order attribute from State interface
  chirho/dynamical/handlers/interruption.py
  chirho/dynamical/internals/_utils.py
  chirho/dynamical/internals/backends/torchdiffeq.py
  chirho/dynamical/ops.py
Labels: status:awaiting review, refactor, feature:dynamics

#324 Fix generic types and arguments of LogTrajectory and StaticBatchObservation
  chirho/dynamical/handlers/interruption.py
  chirho/dynamical/handlers/trajectory.py
  tests/dynamical/test_dynamic_interventions.py
  tests/dynamical/test_log_trajectory.py
  tests/dynamical/test_static_interventions.py
Labels: status:awaiting review, refactor, feature:dynamics

#323 Remove usage of Trajectory.__len__
  chirho/dynamical/handlers/interruption.py
  chirho/dynamical/ops.py
Labels: status:awaiting review, refactor, feature:dynamics

#325 Remove Trajectory.__getitem__ method
  chirho/dynamical/handlers/interruption.py
  chirho/dynamical/handlers/trajectory.py
  chirho/dynamical/internals/backends/torchdiffeq.py
  chirho/dynamical/ops.py
  tests/dynamical/test_dynamic_interventions.py
  tests/dynamical/test_static_interventions.py
Labels: status:awaiting review, refactor, feature:dynamics

#330 Separate Observable from InPlaceDynamics interface
  chirho/dynamical/handlers/interruption.py
  chirho/dynamical/ops.py
  tests/dynamical/dynamical_fixtures.py
Labels: status:awaiting review, refactor, feature:dynamics

#327 Remove Trajectory type
  chirho/dynamical/handlers/trajectory.py
  chirho/dynamical/internals/_utils.py
  chirho/dynamical/internals/backends/torchdiffeq.py
  chirho/dynamical/internals/solver.py
  chirho/dynamical/ops.py
  tests/dynamical/dynamical_fixtures.py
  tests/dynamical/test_log_trajectory.py
  tests/dynamical/test_static_interventions.py
Labels: status:awaiting review, refactor, feature:dynamics

#331 Move keys property of State into a helper function get_keys
  chirho/dynamical/handlers/interruption.py
  chirho/dynamical/internals/_utils.py
  chirho/dynamical/internals/backends/torchdiffeq.py
  chirho/dynamical/ops.py
  docs/source/dynamical_intro.ipynb
  tests/dynamical/dynamical_fixtures.py
  tests/dynamical/test_dynamic_interventions.py
  tests/dynamical/test_log_trajectory.py
  tests/dynamical/test_static_interventions.py
Labels: status:awaiting review, refactor, feature:dynamics

#318 Remove notebook_requirements.txt and add nbval to setup.py
  .github/workflows/test_notebooks.yml
  docs/source/notebook_requirements.txt
  setup.py
Labels: status:awaiting review, testing

#339 Remove stale skipped dynamical systems tests
  tests/dynamical/test_dynamic_interventions.py
  tests/dynamical/test_handler_composition.py
  tests/dynamical/test_static_observation.py
Labels: status:awaiting review, refactor, testing, feature:dynamics

#342 Add dynamical sphinx config
  chirho/dynamical/internals/backends/torchdiffeq.py
  chirho/dynamical/internals/solver.py
  docs/source/dynamical.rst
  docs/source/dynamical_intro.ipynb
  docs/source/index.rst
Labels: documentation, status:awaiting review, misc-release, feature:dynamics

#340 Use observe operation in dynamical system observation handlers
  chirho/dynamical/handlers/interruption.py
  chirho/dynamical/internals/_utils.py
  chirho/dynamical/ops.py
  tests/dynamical/dynamical_fixtures.py
  tests/dynamical/test_handler_composition.py
  tests/dynamical/test_static_observation.py
Labels: status:awaiting review, refactor, feature:dynamics

#341 Use functional interface for dynamical systems
  chirho/dynamical/internals/backends/torchdiffeq.py
  chirho/dynamical/internals/solver.py
  chirho/dynamical/ops.py
  tests/dynamical/dynamical_fixtures.py
  tests/dynamical/test_dynamic_interventions.py
  tests/dynamical/test_static_observation.py
Labels: status:awaiting review, refactor, feature:dynamics

#345 Revise CI yml file to run tests in parallel
  .github/workflows/test.yml
Labels: testing

#346 Replace custom State type with Dict
  chirho/dynamical/internals/_utils.py
  chirho/dynamical/internals/backends/torchdiffeq.py
  chirho/dynamical/ops.py
  tests/dynamical/dynamical_fixtures.py
  tests/dynamical/test_dynamic_interventions.py
  tests/dynamical/test_handler_composition.py
  tests/dynamical/test_log_trajectory.py
  tests/dynamical/test_static_interventions.py
  tests/dynamical/test_static_observation.py
Labels: status:awaiting review, refactor, feature:dynamics

#349 Remove get_keys operation
  chirho/dynamical/handlers/interruption.py
  chirho/dynamical/internals/_utils.py
  chirho/dynamical/internals/backends/torchdiffeq.py
  chirho/dynamical/ops.py
  docs/source/dynamical_intro.ipynb
  tests/dynamical/dynamical_fixtures.py
  tests/dynamical/test_dynamic_interventions.py
  tests/dynamical/test_log_trajectory.py
  tests/dynamical/test_static_interventions.py
Labels: status:awaiting review, refactor, feature:dynamics

#352 Revise dynamical systems notebook to work with recent refactoring changes
  docs/source/dynamical_intro.ipynb
Labels: status:awaiting review, examples, feature:dynamics

#241 Operations and Handlers for Dynamical Systems
  .github/workflows/lint.yml
  .github/workflows/test.yml
  chirho/dynamical/__init__.py
  chirho/dynamical/handlers/__init__.py
  chirho/dynamical/handlers/event_loop.py
  chirho/dynamical/handlers/interruption.py
  chirho/dynamical/handlers/solver.py
  chirho/dynamical/handlers/trajectory.py
  chirho/dynamical/internals/__init__.py
  chirho/dynamical/internals/_utils.py
  chirho/dynamical/internals/backends/__init__.py
  chirho/dynamical/internals/backends/torchdiffeq.py
  chirho/dynamical/internals/solver.py
  chirho/dynamical/ops.py
  docs/source/dynamical.rst
  docs/source/dynamical_intro.ipynb
  docs/source/index.rst
  docs/source/requirements.txt
  setup.py
  tests/dynamical/__init__.py
  tests/dynamical/dynamical_fixtures.py
  tests/dynamical/test_dynamic_interventions.py
  tests/dynamical/test_handler_composition.py
  tests/dynamical/test_log_trajectory.py
  tests/dynamical/test_noop_interruptions.py
  tests/dynamical/test_solver.py
  tests/dynamical/test_static_interventions.py
  tests/dynamical/test_static_observation.py
Labels: feature:dynamics, staging-branch

#356 Separate `simulate` from `simulate_to_interruption`
  chirho/dynamical/handlers/event_loop.py
  chirho/dynamical/handlers/interruption.py
  chirho/dynamical/handlers/trajectory.py
  chirho/dynamical/internals/solver.py
  chirho/dynamical/ops.py
Labels: status:awaiting review, refactor, feature:dynamics

#358 Remove eps from core dynamics module, instead relying on backend-specific implementations to handle time collisions
  chirho/dynamical/handlers/interruption.py
  chirho/dynamical/handlers/trajectory.py
  chirho/dynamical/internals/backends/torchdiffeq.py
  tests/dynamical/test_noop_interruptions.py
  tests/dynamical/test_static_interventions.py
Labels: status:awaiting review, refactor, feature:dynamics

#359 Add error handling and warning when interruption is outside of `simulate` start and end time
  chirho/dynamical/handlers/interruption.py
  tests/dynamical/test_static_interventions.py
Labels: bug, status:awaiting review, testing, feature:dynamics

#360 Add shallow effect handler base class
  chirho/dynamical/internals/_utils.py
  tests/dynamical/test_handler_composition.py
Labels: enhancement, status:awaiting review, refactor, feature:dynamics

#362 adding ExplainCauses
  chirho/counterfactual/handlers/explanation.py
  tests/counterfactual/test_handlers_explanation.py
Labels: status:WIP

#363 Fix bugged interaction between `LogTrajectory` and `Interruption` when times collide
  chirho/dynamical/handlers/trajectory.py
  tests/dynamical/test_log_trajectory.py
Labels: bug, status:awaiting review, feature:dynamics
