Repository BasisResearch/chirho, pull requests merged in 2023-12, with the labels that each got.

#308 adding notebook tests
  .github/workflows/test_notebooks.yml
  .gitignore
  docs/source/backdoor.ipynb
  docs/source/cevae.ipynb
  docs/source/dr_learner.ipynb
  docs/source/mediation.ipynb
  docs/source/sdid.ipynb
  docs/source/slc.ipynb
  docs/source/tutorial_i.ipynb
  scripts/test_notebooks.sh
  setup.py
Labels: status:awaiting review, testing

#414 add `preempt` and its tests
  chirho/explainable/ops.py
  tests/explainable/test_ops.py
Labels: status:awaiting review, feature:causality

#416 added uniform proposal
  chirho/explainable/internals/defaults.py
  tests/explainable/defaults/test_defaults.py
Labels: status:awaiting review, feature:causality

#422 add `undo_split` and a test thereof
  chirho/explainable/handlers/__init__.py
  chirho/explainable/handlers/split_subsets.py
  tests/explainable/test_split_subsets.py
Labels: status:awaiting review, feature:causality

#418 add consequent_differs and a test thereof
  chirho/explainable/ops.py
  tests/explainable/test_ops.py
Labels: status:awaiting review, feature:causality

#424 added SplitSubsets and a test thereof
  chirho/explainable/handlers/__init__.py
  chirho/explainable/handlers/split_subsets.py
  tests/explainable/test_split_subsets.py
Labels: status:awaiting review, feature:causality

#405 Added more tests for `linearize` and `make_empirical_fisher_vp`
  tests/robust/__init__.py
  tests/robust/robust_fixtures.py
  tests/robust/test_internals_compositions.py
  tests/robust/test_internals_linearize.py
  tests/robust/test_ops.py
Labels: status:awaiting review, testing, feature:robust

#397 Fix time collision bug in `LogTrajectory`
  chirho/dynamical/handlers/interruption.py
  chirho/dynamical/handlers/trajectory.py
  chirho/dynamical/internals/_utils.py
  tests/dynamical/test_log_trajectory.py
  tests/dynamical/test_static_interventions.py
Labels: bug, status:awaiting review, feature:dynamics

#426 Remove deprecated `event_loop` module from Sphinx
  docs/source/dynamical.rst
Labels: bug, documentation, status:awaiting review

#425 Add CONTRIBUTING to sphinx docs
  CONTRIBUTING.md
  CONTRIBUTING.rst
  docs/source/contributing.rst
  docs/source/index.rst
Labels: documentation, status:awaiting review

#377 Revise basic SIR tutorial
  .github/workflows/test_notebooks.yml
  chirho/dynamical/handlers/interruption.py
  chirho/dynamical/handlers/trajectory.py
  docs/source/dynamical_intro.ipynb
  scripts/test_notebooks.sh
Labels: status:awaiting review, examples, feature:dynamics

#433 Make State into a type alias of Mapping
  chirho/dynamical/handlers/trajectory.py
  chirho/dynamical/internals/_utils.py
  chirho/dynamical/internals/backends/torchdiffeq.py
  chirho/dynamical/ops.py
  docs/source/dynamical_intro.ipynb
  tests/dynamical/dynamical_fixtures.py
  tests/dynamical/test_dynamic_interventions.py
  tests/dynamical/test_handler_composition.py
  tests/dynamical/test_log_trajectory.py
  tests/dynamical/test_noop_interruptions.py
  tests/dynamical/test_solver.py
  tests/dynamical/test_static_interventions.py
  tests/dynamical/test_static_observation.py
  tests/dynamical/test_validate_dynamics.py
Labels: status:awaiting review, refactor, feature:dynamics

#434 Add dynamical requirements to test requirements
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .github/workflows/test_notebooks.yml
  setup.py
Labels: documentation, status:awaiting review, misc-release

#404 Add upper bound on number of CG steps
  chirho/robust/internals/linearize.py
Labels: enhancement, status:awaiting review, feature:robust

#437 Fix non-symmetric matrix issue in `test_cg_solve` and `test_batch_cg_solve`
  tests/robust/test_internals_linearize.py
Labels: bug, status:awaiting review, feature:robust

#442 add `random intervention` and a test thereof
  chirho/explainable/handlers/__init__.py
  chirho/explainable/handlers/alternatives.py
  chirho/explainable/internals/__init__.py
  tests/explainable/test_alternatives.py
Labels: status:awaiting review, feature:causality

#445 add `SearchForExplanation`
  chirho/explainable/handlers/__init__.py
  chirho/explainable/handlers/explanation.py
  chirho/explainable/handlers/split_subsets.py
  tests/explainable/test_explanation.py
Labels: status:awaiting review, feature:causality

#408 Make `NMCLogPredictiveLikelihood` seeded
  chirho/robust/internals/linearize.py
  chirho/robust/internals/predictive.py
  chirho/robust/internals/utils.py
  tests/robust/test_internals_compositions.py
Labels: status:awaiting review, testing, feature:robust

#430 Use Hessian formulation of Fisher information in `make_empirical_fisher_vp`
  chirho/robust/internals/linearize.py
Labels: enhancement, status:awaiting review, feature:robust

#439 Add documentation for `dynamical.ops` and `dynamical.handlers`
  chirho/dynamical/handlers/interruption.py
  chirho/dynamical/handlers/solver.py
  chirho/dynamical/handlers/trajectory.py
  chirho/dynamical/ops.py
  docs/source/dynamical.rst
  docs/source/dynamical_type_aliases.rst
Labels: documentation, status:awaiting review, feature:dynamics

#438 Add a generic on() operation to dynamical
  chirho/dynamical/handlers/interruption.py
  chirho/dynamical/internals/backends/torchdiffeq.py
  chirho/dynamical/internals/solver.py
  chirho/dynamical/ops.py
Labels: status:awaiting review, refactor, feature:dynamics

#452 Bump version to 0.2.0
  setup.py
Labels: status:awaiting review, misc-release

#457 explainable documentation update
  chirho/explainable/handlers/explanation.py
  chirho/explainable/handlers/preemptions.py
  chirho/explainable/handlers/split_subsets.py
  chirho/explainable/internals/defaults.py
Labels: status:awaiting review, feature:causality

#458 Remove explainable references from chirho.counterfactual
  chirho/counterfactual/handlers/counterfactual.py
  docs/source/counterfactual.rst
Labels: documentation, status:awaiting review

#465 Batching in `linearize` and `influence`
  chirho/robust/internals/linearize.py
  chirho/robust/ops.py
  tests/robust/test_internals_linearize.py
  tests/robust/test_ops.py
Labels: enhancement, status:awaiting review, feature:robust

#466 Batching `_flat_conjugate_gradient_solve` in `chirho.robust`
  chirho/robust/internals/linearize.py
  chirho/robust/internals/utils.py
  tests/robust/test_internals_compositions.py
  tests/robust/test_internals_linearize.py
Labels: enhancement, feature:robust

#467 One step correction implemented
  chirho/robust/handlers/estimators.py
  tests/robust/test_handlers.py
  tests/robust/test_internals_linearize.py
Labels: enhancement, feature:robust
