Repository BasisResearch/chirho, pull requests merged in 2023-07, with the labels that each got.

#194 Add requirements.txt for docs workflow
  .github/workflows/publish_docs.yml
  docs/source/requirements.txt
Labels: misc-release

#175 Add observe operation and new condition handler
  chirho/interventional/handlers.py
  chirho/observational/__init__.py
  chirho/observational/handlers/__init__.py
  chirho/observational/handlers/condition.py
  chirho/observational/handlers/soft_conditioning.py
  chirho/observational/internals.py
  chirho/observational/ops.py
  tests/observational/test_handlers.py
Labels: bug, awaiting review, refactor, testing

#195 Add path to docs/source/conf.py for sphinx deployment
  docs/source/conf.py
Labels: misc-release

#205 Restores (via cherry-pick) Notebook Link and Formatting Changes
  docs/source/backdoor.ipynb
  docs/source/cevae.ipynb
  docs/source/deepscm.ipynb
  docs/source/mediation.ipynb
  docs/source/slc.ipynb
Labels: awaiting review

#176 Refactor counterfactuals to use observe and condition
  chirho/counterfactual/handlers/ambiguity.py
  chirho/counterfactual/handlers/counterfactual.py
  chirho/counterfactual/internals.py
  chirho/indexed/handlers.py
  docs/source/backdoor.ipynb
  docs/source/cevae.ipynb
  docs/source/counterfactual.rst
  docs/source/deepscm.ipynb
  docs/source/mediation.ipynb
  docs/source/observational.rst
  docs/source/slc.ipynb
  tests/counterfactual/test_ambiguity.py
  tests/counterfactual/test_counterfactual_handler.py
  tests/counterfactual/test_mediation.py
  tests/counterfactual/test_selection.py
Labels: bug, awaiting review, refactor, testing

#206 Fixed symbolic link in tutorial
  docs/source/tutorial_i.ipynb
Labels: documentation, awaiting review

#209 Fix image duplication in intro tutorial
  docs/source/design_notes/interventions.rst
  docs/source/tutorial_i.ipynb
Labels: bug, documentation, awaiting review

#208 Bump version to 0.1.0-alpha
  setup.py
Labels: awaiting review, misc-release

#218 Cleanup of Performance Improvements for ODE Conditioning
  chirho/dynamical/handlers.py
  tests/dynamical/dynamical_fixtures.py
  tests/dynamical/test_static_observation.py
Labels: awaiting review

#216 Add logo to README and getting_started
  README.rst
  docs/source/getting_started.rst
Labels: awaiting review, misc-release

#220 Fix PyroModule state persistence in simulate
  chirho/dynamical/handlers.py
  tests/dynamical/test_static_observation.py
Labels: bug, awaiting review, feature:dynamics

#225 Switch to local PyroParams in tests
  tests/counterfactual/test_counterfactual_handler.py
  tests/observational/test_handlers.py
Labels: bug, awaiting review, testing

#219 Test Composition of Dynamic Counterfactual and Observation
  chirho/dynamical/handlers.py
  chirho/dynamical/ops.py
  tests/dynamical/dynamical_fixtures.py
  tests/dynamical/test_dynamic_interventions.py
  tests/dynamical/test_handler_composition.py
  tests/dynamical/test_noop_interruptions.py
  tests/dynamical/test_static_interventions.py
  tests/dynamical/test_static_observation.py
Labels: awaiting review, testing, feature:dynamics

#226 both factual outcomes -> both outcomes
  docs/source/tutorial_i.ipynb
Labels: documentation, awaiting review

#224 Added test to check output of estimating counterfactual with AutoSoftConditioning
  tests/counterfactual/test_counterfactual_handler.py
Labels: awaiting review, testing

#223 Added counterfactual example to the demo
  docs/source/dynamical_intro.ipynb
Labels: awaiting review, examples, feature:dynamics
