Repository BasisResearch/chirho, pull requests merged in 2023-09, with the labels that each got.

#238 Add an effect handler for inserting factor statements
  chirho/observational/handlers/condition.py
  tests/observational/test_handlers.py
Labels: enhancement, status:awaiting review, feature:causality

#254 Updated copyright on docs to 2023
  docs/source/conf.py
Labels: documentation, status:awaiting review

#262 Fix docs deployment to GH-pages by pinning sphinx_rtd_theme to 1.3.0
  docs/source/requirements.txt
  setup.py
Labels: bug, documentation, status:awaiting review

#258 Fix inference in backdoor adjustment example
  docs/source/backdoor.ipynb
Labels: status:awaiting review, examples

#271 Make example documentation headers consistently formatted
  docs/source/backdoor.ipynb
  docs/source/cevae.ipynb
  docs/source/deepscm.ipynb
  docs/source/mediation.ipynb
  docs/source/slc.ipynb
Labels: documentation, status:awaiting review

#274 Make tutorial run end to end
  docs/source/tutorial_i.ipynb
Labels: bug, status:awaiting review

#265 Single-Cell RNA Seq Example
  docs/source/figures/sciplex_fig1b.png
  docs/source/figures/sciplex_fig3a.png
  docs/source/figures/sciplex_fig5b.png
  docs/source/sciplex.ipynb
Labels: status:awaiting review, examples

#275 Document counterfactual operations and handlers
  chirho/counterfactual/handlers/counterfactual.py
  chirho/counterfactual/ops.py
Labels: documentation, status:WIP

#277 Add RNAseq example to readme and docs
  README.rst
  docs/source/index.rst
  docs/source/sciplex.ipynb
Labels: documentation

#278 Fix docstring propagation in counterfactual ops
  chirho/counterfactual/ops.py
Labels: documentation, status:awaiting review

#280 Fix TOC link for single RNA seq example notebook
  docs/source/sciplex.ipynb
Labels: bug, status:awaiting review

#279 Bump version to 0.1.0
  setup.py
Labels: status:awaiting review, misc-release, blocked

#264 Adding undo_split and a test thereof (+small lint)
  chirho/counterfactual/handlers/explanation.py
  docs/source/counterfactual.rst
  tests/counterfactual/test_handlers_explanation.py
Labels: enhancement, status:awaiting review, feature:causality

#250 Replace Preemptions handler implementation
  chirho/counterfactual/handlers/counterfactual.py
  tests/counterfactual/test_counterfactual_handler.py
Labels: status:awaiting review, refactor, feature:causality

#268 Ru consequent differs
  chirho/counterfactual/handlers/explanation.py
  tests/counterfactual/test_handlers_explanation.py
Labels: status:awaiting review, feature:causality

#285 Minor fix to formatting of code snippets in documentation
  chirho/counterfactual/handlers/counterfactual.py
  chirho/indexed/ops.py
Labels: documentation

#286 Refactor dynamical module file structure to be consistent with other modules
  chirho/dynamical/handlers.py
  chirho/dynamical/internals/ODE/__init__.py
  chirho/dynamical/internals/__init__.py
  chirho/dynamical/internals/dynamical.py
  chirho/dynamical/internals/indexed.py
  chirho/dynamical/internals/interruption.py
  chirho/dynamical/internals/interventional.py
  chirho/dynamical/ops.py
  chirho/dynamical/ops/ODE/__init__.py
  chirho/dynamical/ops/__init__.py
  chirho/dynamical/ops/dynamical.py
  tests/dynamical/dynamical_fixtures.py
  tests/dynamical/test_dynamic_interventions.py
  tests/dynamical/test_handler_composition.py
  tests/dynamical/test_noop_interruptions.py
  tests/dynamical/test_static_interventions.py
  tests/dynamical/test_static_observation.py
Labels: status:awaiting review, refactor, feature:dynamics

#290 Decouple ODEDynamics class from TorchDiffEq
  chirho/dynamical/__init__.py
  chirho/dynamical/handlers/__init__.py
  chirho/dynamical/handlers/dynamical.py
  chirho/dynamical/handlers/interruption.py
  chirho/dynamical/handlers/solver.py
  chirho/dynamical/internals/ODE/__init__.py
  chirho/dynamical/internals/ODE/backends/__init__.py
  chirho/dynamical/internals/ODE/backends/torchdiffeq.py
  chirho/dynamical/internals/ODE/ode_simulate.py
  chirho/dynamical/internals/__init__.py
  chirho/dynamical/internals/interruption.py
  chirho/dynamical/ops/ODE/__init__.py
  chirho/dynamical/ops/ODE/ode.py
  chirho/dynamical/ops/ODE/solvers/__init__.py
  chirho/dynamical/ops/ODE/solvers/torchdiffeq.py
  chirho/dynamical/ops/__init__.py
  chirho/dynamical/ops/dynamical.py
  docs/source/dynamical_intro.ipynb
  tests/dynamical/obs_runtime.py
  tests/dynamical/test_dynamic_interventions.py
  tests/dynamical/test_handler_composition.py
  tests/dynamical/test_noop_interruptions.py
  tests/dynamical/test_solver.py
  tests/dynamical/test_static_interventions.py
  tests/dynamical/test_static_observation.py
Labels: status:awaiting review, refactor, feature:dynamics

#292 Consolidate `Backend` and `SolverHandler` into a single `Solver` effect handler / dispatch mechanism
  chirho/dynamical/handlers/ODE/__init__.py
  chirho/dynamical/handlers/ODE/ode.py
  chirho/dynamical/handlers/ODE/solvers/__init__.py
  chirho/dynamical/handlers/ODE/solvers/torchdiffeq.py
  chirho/dynamical/handlers/__init__.py
  chirho/dynamical/handlers/dynamical.py
  chirho/dynamical/handlers/interruption.py
  chirho/dynamical/handlers/solver.py
  chirho/dynamical/internals/ODE/backends/torchdiffeq.py
  chirho/dynamical/internals/ODE/ode_simulate.py
  chirho/dynamical/internals/indexed.py
  chirho/dynamical/internals/interruption.py
  chirho/dynamical/internals/interventional.py
  chirho/dynamical/ops/ODE.py
  chirho/dynamical/ops/ODE/__init__.py
  chirho/dynamical/ops/__init__.py
  chirho/dynamical/ops/dynamical.py
  docs/source/dynamical_intro.ipynb
  tests/dynamical/dynamical_fixtures.py
  tests/dynamical/obs_runtime.py
  tests/dynamical/test_dynamic_interventions.py
  tests/dynamical/test_handler_composition.py
  tests/dynamical/test_noop_interruptions.py
  tests/dynamical/test_solver.py
  tests/dynamical/test_static_interventions.py
  tests/dynamical/test_static_observation.py
Labels: status:awaiting review, refactor, feature:dynamics, staging-branch
