Repository BasisResearch/chirho, pull requests merged in 2024-04, with the labels that each got.

#533 Revise tutorial with broadcastable models and counterfactual indexing
  docs/source/tutorial_i.ipynb
Labels: documentation, status:awaiting review

#534 simplify `AutoSoftConditioningReparam` to use `soft_eq` directly.
  chirho/observational/handlers/soft_conditioning.py
  tests/counterfactual/test_counterfactual_handler.py
  tests/dynamical/test_handler_composition.py
  tests/observational/test_handlers.py
Labels: status:awaiting review, refactor, module:observational

#535 introduce notebook cleaning and linting scripts with an example
  Makefile
  docs/source/tutorial_i.ipynb
  scripts/clean_notebooks.sh
  scripts/lint_notebooks.sh
  setup.py
Labels: status:awaiting review, testing

#528 Reuse non-default names across multiple splits in MultiWorldCounterfactual
  chirho/counterfactual/handlers/counterfactual.py
  chirho/counterfactual/ops.py
  chirho/indexed/internals.py
  tests/counterfactual/test_mediation.py
  tests/dynamical/test_dynamic_interventions.py
  tests/dynamical/test_static_interventions.py
Labels: enhancement, status:awaiting review, blocked, module:counterfactual

#539 Fix tutorial to pass notebook CI tests
  docs/source/tutorial_i.ipynb
Labels: bug, documentation, status:awaiting review, testing

#541 Revise counterfactual tests to use `indexed` operations.
  tests/counterfactual/test_counterfactual_handler.py
  tests/counterfactual/test_mediation.py
Labels: status:awaiting review, refactor, testing
