Repository BasisResearch/chirho, pull requests merged in 2025-03, with the labels that each got.

#579 Address linting errors in `dynamical`
  chirho/dynamical/handlers/interruption.py
  chirho/dynamical/internals/solver.py
  chirho/dynamical/ops.py
  chirho/robust/internals/utils.py
Labels: status:awaiting review

#581 Bump deprecated GitHub CI actions and cache v1/v2 to v4
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .github/workflows/test_notebooks.yml
Labels: status:awaiting review

#580 Fix bug in `dynamical` module when two dynamic interventions occur at the same time
  chirho/dynamical/internals/backends/torchdiffeq.py
  tests/dynamical/test_dynamic_interventions.py
Labels: status:awaiting review

#565 Documentation for `explainable` for model with continuous variables
  chirho/dynamical/internals/solver.py
  docs/source/explainable_categorical.ipynb
  docs/source/explainable_sir.ipynb
  docs/source/index.rst
Labels: documentation, status:awaiting review, module:explainable

#542 Multilevel model tutorial with dynamical systems
  docs/source/dynamical_intro.ipynb
  docs/source/dynamical_multi.ipynb
  docs/source/index.rst
Labels: documentation, status:awaiting review, module:dynamical
